insert into Country values (1, 'Peru');
insert into Country values (2, 'Bolivia');
insert into Country values (3, 'Chile');
insert into Country values (4, 'Brasil');
insert into Country values (5, 'Venezuela');
insert into Country values (6, 'Argentina');
insert into Country values (7, 'Colombia');
insert into Country values (8, 'Uruguay');
insert into Country values (9, 'Paraguay');
insert into Country values (10, 'Ecuador');
insert into City(name, countryId) values ('Lima', 1);
insert into City(name, countryId) values ('Ica', 1);
insert into City(name, countryId) values ('Santa Cruz', 2);
insert into City(name, countryId) values ('Sucre', 2);
insert into City(name, countryId) values ('Caracas', 5);
insert into City(name, countryId) values ('Ouro Preto', 4);
insert into City(name, countryId) values ('Minas Gerais', 4);
insert into City(name, countryId) values ('Jujuy', 6);
insert into City(name, countryId) values ('Neuquén ', 6);
insert into City(name, countryId) values ('Río Negro ', 6);
insert into City(name, countryId) values ('Bogota', 7);
insert into City(name, countryId) values ('Arica', 3);
insert into City(name, countryId) values ('Valparaiso', 3);

